# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{omniture-rails}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Higginbotham"]
  s.date = %q{2010-06-27}
  s.description = %q{Tool for integrating Omniture in a Rails project}
  s.email = %q{daniel@flyingmachinestudios.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "app/helpers/omniture_rails_helper.rb",
     "app/views/shared/_omniture.html.haml",
     "app/views/shared/_omniture_javascript.html.haml",
     "lib/omniture-rails.rb",
     "lib/omniture-rails/applier.rb",
     "lib/omniture-rails/config.rb",
     "lib/omniture-rails/node.rb",
     "lib/omniture-rails/parser.rb",
     "lib/omniture-rails/value.rb",
     "omniture-rails.gemspec",
     "rails/action_controller_extension.rb",
     "rails/concern.rb",
     "rails/init.rb",
     "spec/fixtures/application.sc",
     "spec/fixtures/config.yml",
     "spec/fixtures/search.sc",
     "spec/fixtures/selectors_with_groups.sc",
     "spec/fixtures/with_import.sc",
     "spec/lib/omniture-rails/applier_spec.rb",
     "spec/lib/omniture-rails/config_spec.rb",
     "spec/lib/omniture-rails/parser_spec.rb",
     "spec/omniture-rails_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/flyingmachine/omniture-rails}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Tool for integrating Omniture in a Rails project}
  s.test_files = [
    "spec/lib/omniture-rails/applier_spec.rb",
     "spec/lib/omniture-rails/config_spec.rb",
     "spec/lib/omniture-rails/parser_spec.rb",
     "spec/omniture-rails_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.3.0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.3.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.3.0"])
  end
end

